from __future__ import annotations

from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest
from unittest.mock import patch

from ai_dev_flow.alias_config import DesiredAliasState
from ai_dev_flow.alias_installation import (
    AliasInstallationError,
    AliasInstallerPaths,
    _sha256_text,
    _ensure_manifest_owned_alias_file,
    _paths_equal,
    _profile_source_line,
    apply_alias_reconciliation,
    resolve_installer_paths,
)
from ai_dev_flow.installation_manifest import InstallationManifest, MANIFEST_VERSION, load_manifest


class AliasInstallationTests(unittest.TestCase):
    def setUp(self) -> None:
        self._tmpdir = tempfile.TemporaryDirectory()
        self.tmp_path = Path(self._tmpdir.name)
        self.paths = AliasInstallerPaths(
            profile_path=self.tmp_path / "profile.rc",
            alias_file_path=self.tmp_path / "aliases.sh",
            manifest_path=self.tmp_path / "manifest.json",
        )

    def tearDown(self) -> None:
        self._tmpdir.cleanup()

    def test_apply_writes_posix_function_aliases(self) -> None:
        desired = DesiredAliasState(aliases={"review": "review", "gs": "status"})

        summary = apply_alias_reconciliation(desired, installer_paths=self.paths, force_windows=False)

        self.assertEqual(summary.aliases_configured, 2)
        self.assertEqual(summary.outcome, "applied")
        self.assertTrue(self.paths.alias_file_path.exists())
        alias_text = self.paths.alias_file_path.read_text(encoding="utf-8")
        self.assertNotIn("set -e", alias_text)
        self.assertIn("review() {", alias_text)
        self.assertIn('    command ai-dev review "$@"', alias_text)
        self.assertIn("gs() {", alias_text)
        self.assertIn('    command ai-dev status "$@"', alias_text)
        if shutil.which("sh"):
            subprocess.run(
                ["sh", "-n", str(self.paths.alias_file_path)],
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                encoding="utf-8",
            )

    def test_apply_writes_powershell_direct_functions(self) -> None:
        desired = DesiredAliasState(aliases={"review": "review"})
        paths = AliasInstallerPaths(
            profile_path=self.tmp_path / "profile.ps1",
            alias_file_path=self.tmp_path / "aliases.ps1",
            manifest_path=self.tmp_path / "manifest.json",
        )

        apply_alias_reconciliation(desired, installer_paths=paths, force_windows=True)

        alias_text = paths.alias_file_path.read_text(encoding="utf-8")
        self.assertIn("function review {", alias_text)
        self.assertIn("    & ai-dev review @args", alias_text)
        self.assertNotIn("Invoke-Expression", alias_text)

    def test_apply_empty_aliases_removes_managed_files(self) -> None:
        desired = DesiredAliasState(aliases={"gs": "status"})
        apply_alias_reconciliation(desired, installer_paths=self.paths, force_windows=False)

        empty = DesiredAliasState(aliases={})
        summary = apply_alias_reconciliation(empty, installer_paths=self.paths, force_windows=False)

        self.assertEqual(summary.aliases_configured, 0)
        self.assertEqual(summary.outcome, "removed-all")
        self.assertFalse(self.paths.alias_file_path.exists())
        self.assertFalse(self.paths.manifest_path.exists())
        self.assertTrue(summary.manifest_removed)

    def test_apply_empty_aliases_noop_when_nothing_managed(self) -> None:
        summary = apply_alias_reconciliation(
            DesiredAliasState(aliases={}),
            installer_paths=self.paths,
            force_windows=False,
        )
        self.assertEqual(summary.outcome, "no-op")
        self.assertFalse(summary.manifest_removed)

    def test_manifest_failure_rolls_back_file_changes(self) -> None:
        self.paths.profile_path.write_text("before\n", encoding="utf-8")
        self.paths.alias_file_path.write_text("# Generated by ai-dev. DO NOT EDIT.\nold\n", encoding="utf-8")

        desired = DesiredAliasState(aliases={"gs": "status"})
        with patch(
            "ai_dev_flow.alias_installation.save_manifest",
            side_effect=RuntimeError("manifest write failed"),
        ):
            with self.assertRaises(AliasInstallationError):
                apply_alias_reconciliation(desired, installer_paths=self.paths, force_windows=False)

        self.assertEqual(self.paths.profile_path.read_text(encoding="utf-8"), "before\n")
        self.assertEqual(
            self.paths.alias_file_path.read_text(encoding="utf-8"),
            "# Generated by ai-dev. DO NOT EDIT.\nold\n",
        )

    def test_remove_all_is_transactional(self) -> None:
        desired = DesiredAliasState(aliases={"gs": "status"})
        apply_alias_reconciliation(desired, installer_paths=self.paths, force_windows=False)

        before_alias = self.paths.alias_file_path.read_text(encoding="utf-8")
        before_profile = self.paths.profile_path.read_text(encoding="utf-8")
        before_manifest = self.paths.manifest_path.read_text(encoding="utf-8")

        with patch(
            "pathlib.Path.unlink",
            side_effect=OSError("unlink failed"),
        ):
            with self.assertRaises(AliasInstallationError):
                apply_alias_reconciliation(
                    DesiredAliasState(aliases={}),
                    installer_paths=self.paths,
                    force_windows=False,
                )

        self.assertEqual(self.paths.alias_file_path.read_text(encoding="utf-8"), before_alias)
        self.assertEqual(self.paths.profile_path.read_text(encoding="utf-8"), before_profile)
        self.assertEqual(self.paths.manifest_path.read_text(encoding="utf-8"), before_manifest)

    def test_reports_rollback_failures(self) -> None:
        desired = DesiredAliasState(aliases={"gs": "status"})
        self.paths.alias_file_path.write_text("# Generated by ai-dev. DO NOT EDIT.\nold\n", encoding="utf-8")

        with (
            patch("ai_dev_flow.alias_installation.save_manifest", side_effect=RuntimeError("boom")),
            patch(
                "ai_dev_flow.alias_installation._restore_from_snapshot",
                return_value=["restore alias file /tmp/aliases.sh: denied"],
            ),
        ):
            with self.assertRaises(AliasInstallationError) as ctx:
                apply_alias_reconciliation(desired, installer_paths=self.paths, force_windows=False)

        self.assertIn("rollback failures", str(ctx.exception))
        self.assertIn("restore alias file /tmp/aliases.sh: denied", str(ctx.exception))

    def test_rejects_divergent_user_owned_alias_file(self) -> None:
        self.paths.alias_file_path.write_text("unaligned user file\n", encoding="utf-8")
        with self.assertRaises(AliasInstallationError):
            apply_alias_reconciliation(
                DesiredAliasState(aliases={"gs": "status"}),
                installer_paths=self.paths,
                force_windows=False,
            )

    def test_noop_when_desired_matches_existing_and_manifest(self) -> None:
        desired = DesiredAliasState(aliases={"gs": "status"})
        first = apply_alias_reconciliation(desired, installer_paths=self.paths, force_windows=False)
        self.assertEqual(first.outcome, "applied")

        second = apply_alias_reconciliation(desired, installer_paths=self.paths, force_windows=False)
        self.assertEqual(second.outcome, "no-op")
        self.assertFalse(second.manifest_written)

    def test_migrates_bash_profile_to_zsh_profile(self) -> None:
        home = self.tmp_path / "home"
        bash_paths = AliasInstallerPaths(
            profile_path=home / ".bashrc",
            alias_file_path=home / ".config" / "ai-dev" / "aliases.sh",
            manifest_path=home / ".config" / "ai-dev" / "managed-aliases-manifest.json",
        )
        zsh_paths = AliasInstallerPaths(
            profile_path=home / ".zshrc",
            alias_file_path=home / ".config" / "ai-dev" / "aliases.sh",
            manifest_path=home / ".config" / "ai-dev" / "managed-aliases-manifest.json",
        )

        apply_alias_reconciliation(
            DesiredAliasState(aliases={"gs": "status"}),
            installer_paths=bash_paths,
            force_windows=False,
        )

        summary = apply_alias_reconciliation(
            DesiredAliasState(aliases={"gs": "status"}),
            installer_paths=zsh_paths,
            force_windows=False,
        )

        self.assertEqual(summary.outcome, "migrated")
        self.assertEqual(summary.previous_profile_path, bash_paths.profile_path)
        self.assertEqual(summary.profile_path, zsh_paths.profile_path)
        self.assertNotIn("ai-dev managed aliases", bash_paths.profile_path.read_text(encoding="utf-8"))
        self.assertIn("ai-dev managed aliases", zsh_paths.profile_path.read_text(encoding="utf-8"))

        manifest = load_manifest(zsh_paths.manifest_path)
        assert manifest is not None
        self.assertEqual(manifest.profile_path, zsh_paths.profile_path)

    def test_profile_only_migration_refuses_tampered_shared_alias_file(self) -> None:
        home = self.tmp_path / "home-profile-only-tampered"
        bash_paths = AliasInstallerPaths(
            profile_path=home / ".bashrc",
            alias_file_path=home / ".config" / "ai-dev" / "aliases.sh",
            manifest_path=home / ".config" / "ai-dev" / "managed-aliases-manifest.json",
        )
        zsh_paths = AliasInstallerPaths(
            profile_path=home / ".zshrc",
            alias_file_path=home / ".config" / "ai-dev" / "aliases.sh",
            manifest_path=home / ".config" / "ai-dev" / "managed-aliases-manifest.json",
        )

        apply_alias_reconciliation(
            DesiredAliasState(aliases={"gs": "status"}),
            installer_paths=bash_paths,
            force_windows=False,
        )
        old_profile_before = bash_paths.profile_path.read_text(encoding="utf-8")
        old_manifest_before = bash_paths.manifest_path.read_text(encoding="utf-8")
        alias_before = bash_paths.alias_file_path.read_text(encoding="utf-8")

        bash_paths.alias_file_path.write_text(alias_before + "# tampered\n", encoding="utf-8")

        with self.assertRaises(AliasInstallationError):
            apply_alias_reconciliation(
                DesiredAliasState(aliases={"gs": "status"}),
                installer_paths=zsh_paths,
                force_windows=False,
            )

        self.assertEqual(bash_paths.profile_path.read_text(encoding="utf-8"), old_profile_before)
        self.assertFalse(zsh_paths.profile_path.exists())
        self.assertEqual(bash_paths.alias_file_path.read_text(encoding="utf-8"), alias_before + "# tampered\n")
        self.assertEqual(bash_paths.manifest_path.read_text(encoding="utf-8"), old_manifest_before)

    def test_profile_only_migration_refuses_missing_shared_alias_file_before_profile_changes(self) -> None:
        home = self.tmp_path / "home-profile-only-missing"
        bash_paths = AliasInstallerPaths(
            profile_path=home / ".bashrc",
            alias_file_path=home / ".config" / "ai-dev" / "aliases.sh",
            manifest_path=home / ".config" / "ai-dev" / "managed-aliases-manifest.json",
        )
        zsh_paths = AliasInstallerPaths(
            profile_path=home / ".zshrc",
            alias_file_path=home / ".config" / "ai-dev" / "aliases.sh",
            manifest_path=home / ".config" / "ai-dev" / "managed-aliases-manifest.json",
        )

        apply_alias_reconciliation(
            DesiredAliasState(aliases={"gs": "status"}),
            installer_paths=bash_paths,
            force_windows=False,
        )
        old_profile_before = bash_paths.profile_path.read_text(encoding="utf-8")
        old_manifest_before = bash_paths.manifest_path.read_text(encoding="utf-8")

        bash_paths.alias_file_path.unlink()

        with self.assertRaises(AliasInstallationError):
            apply_alias_reconciliation(
                DesiredAliasState(aliases={"gs": "status"}),
                installer_paths=zsh_paths,
                force_windows=False,
            )

        self.assertEqual(bash_paths.profile_path.read_text(encoding="utf-8"), old_profile_before)
        self.assertFalse(zsh_paths.profile_path.exists())
        self.assertFalse(bash_paths.alias_file_path.exists())
        self.assertEqual(bash_paths.manifest_path.read_text(encoding="utf-8"), old_manifest_before)

    def test_windows_path_comparison_semantics_used_on_posix_host(self) -> None:
        self.assertTrue(
            _paths_equal(
                Path("C:/Users/Example/.ai-dev/aliases.ps1"),
                Path("c:/users/example/.AI-DEV/ALIASES.ps1"),
                windows=True,
            )
        )

    def test_manifest_owned_validation_uses_explicit_windows_mode(self) -> None:
        alias_path = self.tmp_path / "CaseSensitiveAlias.ps1"
        alias_text = "# Generated by ai-dev. DO NOT EDIT.\nfunction gs { & ai-dev status @args }\n"
        alias_path.write_text(alias_text, encoding="utf-8")
        manifest = InstallationManifest(
            version=MANIFEST_VERSION,
            profile_path=Path("C:/Users/Example/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1"),
            profile_sha256="a" * 64,
            alias_file_path=Path(str(alias_path).replace("CaseSensitiveAlias.ps1", "casesensitivealias.ps1")),
            alias_file_sha256=_sha256_text(alias_text),
            aliases={"gs": "status"},
        )

        validated_text = _ensure_manifest_owned_alias_file(
            alias_file_path=alias_path,
            prior_manifest=manifest,
            windows=True,
        )
        self.assertEqual(validated_text, alias_text)

    def test_migration_removes_old_alias_file_when_alias_path_changes(self) -> None:
        old_paths = AliasInstallerPaths(
            profile_path=self.tmp_path / "old-profile.rc",
            alias_file_path=self.tmp_path / "old-aliases.sh",
            manifest_path=self.tmp_path / "manifest.json",
        )
        new_paths = AliasInstallerPaths(
            profile_path=self.tmp_path / "new-profile.rc",
            alias_file_path=self.tmp_path / "new-aliases.sh",
            manifest_path=self.tmp_path / "manifest.json",
        )

        apply_alias_reconciliation(
            DesiredAliasState(aliases={"gs": "status"}),
            installer_paths=old_paths,
            force_windows=False,
        )

        summary = apply_alias_reconciliation(
            DesiredAliasState(aliases={"gs": "status"}),
            installer_paths=new_paths,
            force_windows=False,
        )

        self.assertEqual(summary.outcome, "migrated")
        self.assertFalse(old_paths.alias_file_path.exists())
        self.assertTrue(new_paths.alias_file_path.exists())
        manifest = load_manifest(new_paths.manifest_path)
        assert manifest is not None
        self.assertEqual(manifest.alias_file_path, new_paths.alias_file_path)

    def test_migration_failure_restores_old_and_new_paths_and_keeps_old_manifest(self) -> None:
        old_paths = AliasInstallerPaths(
            profile_path=self.tmp_path / "old-profile.rc",
            alias_file_path=self.tmp_path / "old-aliases.sh",
            manifest_path=self.tmp_path / "manifest.json",
        )
        new_paths = AliasInstallerPaths(
            profile_path=self.tmp_path / "new-profile.rc",
            alias_file_path=self.tmp_path / "new-aliases.sh",
            manifest_path=self.tmp_path / "manifest.json",
        )

        apply_alias_reconciliation(
            DesiredAliasState(aliases={"gs": "status"}),
            installer_paths=old_paths,
            force_windows=False,
        )
        old_manifest_text = old_paths.manifest_path.read_text(encoding="utf-8")
        old_profile_text = old_paths.profile_path.read_text(encoding="utf-8")
        old_alias_text = old_paths.alias_file_path.read_text(encoding="utf-8")

        with patch(
            "ai_dev_flow.alias_installation._write_alias_file",
            side_effect=RuntimeError("new alias write failed"),
        ):
            with self.assertRaises(AliasInstallationError):
                apply_alias_reconciliation(
                    DesiredAliasState(aliases={"gs": "status"}),
                    installer_paths=new_paths,
                    force_windows=False,
                )

        self.assertEqual(old_paths.profile_path.read_text(encoding="utf-8"), old_profile_text)
        self.assertEqual(old_paths.alias_file_path.read_text(encoding="utf-8"), old_alias_text)
        self.assertFalse(new_paths.alias_file_path.exists())
        self.assertFalse(new_paths.profile_path.exists())
        self.assertEqual(old_paths.manifest_path.read_text(encoding="utf-8"), old_manifest_text)

    def test_reports_exact_paths_when_rollback_partially_fails_during_migration(self) -> None:
        old_paths = AliasInstallerPaths(
            profile_path=self.tmp_path / "old-profile.rc",
            alias_file_path=self.tmp_path / "old-aliases.sh",
            manifest_path=self.tmp_path / "manifest.json",
        )
        new_paths = AliasInstallerPaths(
            profile_path=self.tmp_path / "new-profile.rc",
            alias_file_path=self.tmp_path / "new-aliases.sh",
            manifest_path=self.tmp_path / "manifest.json",
        )

        apply_alias_reconciliation(
            DesiredAliasState(aliases={"gs": "status"}),
            installer_paths=old_paths,
            force_windows=False,
        )

        with (
            patch(
                "ai_dev_flow.alias_installation._write_alias_file",
                side_effect=RuntimeError("new alias write failed"),
            ),
            patch(
                "ai_dev_flow.alias_installation._restore_from_snapshot",
                return_value=[
                    f"restore file {old_paths.alias_file_path}: denied",
                    f"restore file {new_paths.profile_path}: denied",
                ],
            ),
        ):
            with self.assertRaises(AliasInstallationError) as ctx:
                apply_alias_reconciliation(
                    DesiredAliasState(aliases={"gs": "status"}),
                    installer_paths=new_paths,
                    force_windows=False,
                )

        message = str(ctx.exception)
        self.assertIn(str(old_paths.alias_file_path), message)
        self.assertIn(str(new_paths.profile_path), message)

    def test_refuses_migration_when_old_manifest_alias_file_diverged(self) -> None:
        old_paths = AliasInstallerPaths(
            profile_path=self.tmp_path / "old-profile.rc",
            alias_file_path=self.tmp_path / "old-aliases.sh",
            manifest_path=self.tmp_path / "manifest.json",
        )
        new_paths = AliasInstallerPaths(
            profile_path=self.tmp_path / "new-profile.rc",
            alias_file_path=self.tmp_path / "new-aliases.sh",
            manifest_path=self.tmp_path / "manifest.json",
        )

        apply_alias_reconciliation(
            DesiredAliasState(aliases={"gs": "status"}),
            installer_paths=old_paths,
            force_windows=False,
        )
        old_manifest_text = old_paths.manifest_path.read_text(encoding="utf-8")
        old_profile_text = old_paths.profile_path.read_text(encoding="utf-8")

        old_paths.alias_file_path.write_text("tampered\n", encoding="utf-8")

        with self.assertRaises(AliasInstallationError):
            apply_alias_reconciliation(
                DesiredAliasState(aliases={"gs": "status"}),
                installer_paths=new_paths,
                force_windows=False,
            )

        self.assertEqual(old_paths.profile_path.read_text(encoding="utf-8"), old_profile_text)
        self.assertEqual(old_paths.manifest_path.read_text(encoding="utf-8"), old_manifest_text)
        self.assertFalse(new_paths.profile_path.exists())
        self.assertFalse(new_paths.alias_file_path.exists())

    def test_remove_all_after_shell_change_uses_manifest_paths(self) -> None:
        home = self.tmp_path / "home-remove-shell-change"
        bash_paths = AliasInstallerPaths(
            profile_path=home / ".bashrc",
            alias_file_path=home / ".config" / "ai-dev" / "aliases.sh",
            manifest_path=home / ".config" / "ai-dev" / "managed-aliases-manifest.json",
        )

        apply_alias_reconciliation(
            DesiredAliasState(aliases={"gs": "status"}),
            installer_paths=bash_paths,
            force_windows=False,
        )

        with (
            patch.dict("os.environ", {"HOME": str(home), "SHELL": "/bin/fish"}, clear=False),
            patch("ai_dev_flow.alias_installation.resolve_installer_paths", side_effect=AssertionError("must not resolve shell")),
        ):
            summary = apply_alias_reconciliation(
                DesiredAliasState(aliases={}),
                force_windows=False,
            )

        self.assertEqual(summary.outcome, "removed-all")
        self.assertEqual(summary.alias_file_path, bash_paths.alias_file_path)
        self.assertEqual(summary.profile_path, bash_paths.profile_path)
        self.assertFalse(bash_paths.alias_file_path.exists())
        self.assertFalse(bash_paths.manifest_path.exists())

    def test_remove_all_with_missing_shell_still_cleans_manifest_paths(self) -> None:
        home = self.tmp_path / "home-remove-missing-shell"
        bash_paths = AliasInstallerPaths(
            profile_path=home / ".bashrc",
            alias_file_path=home / ".config" / "ai-dev" / "aliases.sh",
            manifest_path=home / ".config" / "ai-dev" / "managed-aliases-manifest.json",
        )

        apply_alias_reconciliation(
            DesiredAliasState(aliases={"gs": "status"}),
            installer_paths=bash_paths,
            force_windows=False,
        )

        with patch.dict("os.environ", {"HOME": str(home), "SHELL": ""}, clear=False):
            summary = apply_alias_reconciliation(
                DesiredAliasState(aliases={}),
                force_windows=False,
            )

        self.assertEqual(summary.outcome, "removed-all")
        self.assertFalse(bash_paths.alias_file_path.exists())
        self.assertFalse(bash_paths.manifest_path.exists())

    def test_resolve_installer_paths_uses_bash(self) -> None:
        home = self.tmp_path / "home-bash"
        paths = resolve_installer_paths(os_name="posix", shell_program="/bin/bash", home=home)
        self.assertEqual(paths.profile_path, home / ".bashrc")

    def test_resolve_installer_paths_uses_zsh(self) -> None:
        home = self.tmp_path / "home-zsh"
        paths = resolve_installer_paths(os_name="posix", shell_program="/bin/zsh", home=home)
        self.assertEqual(paths.profile_path, home / ".zshrc")

    def test_resolve_installer_paths_rejects_unknown_shell(self) -> None:
        with self.assertRaises(AliasInstallationError):
            resolve_installer_paths(os_name="posix", shell_program="/bin/fish", home=self.tmp_path)

    def test_posix_profile_source_line_escapes_special_path_characters(self) -> None:
        tricky = Path("/tmp/a b/o'brien/$x;(y)/aliases.sh")
        paths = AliasInstallerPaths(
            profile_path=self.tmp_path / "profile-special.rc",
            alias_file_path=tricky,
            manifest_path=self.tmp_path / "manifest-special.json",
        )

        apply_alias_reconciliation(
            DesiredAliasState(aliases={"review_short": "review"}),
            installer_paths=paths,
            force_windows=False,
        )

        profile_text = paths.profile_path.read_text(encoding="utf-8")
        expected = "[ -f '/tmp/a b/o'\"'\"'brien/$x;(y)/aliases.sh' ] && . '/tmp/a b/o'\"'\"'brien/$x;(y)/aliases.sh'"
        self.assertIn(expected, profile_text)

    def test_powershell_profile_source_line_escapes_apostrophes(self) -> None:
        tricky = Path("C:\\Users\\O'Brien\\Folder Name\\$x;(y)\\aliases.ps1")
        profile_text = _profile_source_line(tricky, windows=True)
        expected = ". 'C:\\Users\\O''Brien\\Folder Name\\$x;(y)\\aliases.ps1'"
        self.assertEqual(profile_text, expected)


if __name__ == "__main__":
    unittest.main()
