from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import hashlib
import ntpath
import os
import posixpath
from typing import Iterable

from .alias_config import DesiredAliasState
from .installation_manifest import (
    InstallationManifest,
    InstallationManifestError,
    MANIFEST_VERSION,
    load_manifest,
    save_manifest,
)
from .json_files import JsonFileError, write_text_atomic
from .profile_blocks import (
    ProfileBlockError,
    remove_managed_block,
    upsert_managed_block,
)


class AliasInstallationError(Exception):
    """Raised for managed alias reconciliation failures."""


@dataclass(frozen=True)
class AliasInstallerPaths:
    profile_path: Path
    alias_file_path: Path
    manifest_path: Path


@dataclass(frozen=True)
class AliasApplySummary:
    aliases_configured: int
    alias_file_changed: bool
    profile_changed: bool
    manifest_written: bool
    manifest_removed: bool
    outcome: str
    alias_file_path: Path | None
    profile_path: Path | None
    manifest_path: Path
    previous_alias_file_path: Path | None = None
    previous_profile_path: Path | None = None


@dataclass(frozen=True)
class _InstallSnapshot:
    files: dict[Path, tuple[bool, str]]
    manifest_exists: bool
    manifest: InstallationManifest | None


_GENERATED_HEADER = "# Generated by ai-dev. DO NOT EDIT."


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _read_text_or_empty(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def _render_posix_aliases(aliases: dict[str, str]) -> str:
    lines = [_GENERATED_HEADER, ""]
    for name, target in sorted(aliases.items(), key=lambda item: item[0]):
        lines.append(f"{name}() {{")
        lines.append(f"    command ai-dev {target} \"$@\"")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def _render_powershell_aliases(aliases: dict[str, str]) -> str:
    lines = [_GENERATED_HEADER, ""]
    for name, target in sorted(aliases.items(), key=lambda item: item[0]):
        lines.append(f"function {name} {{")
        lines.append(f"    & ai-dev {target} @args")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def _render_alias_file(aliases: dict[str, str], *, windows: bool) -> str:
    if windows:
        return _render_powershell_aliases(aliases)
    return _render_posix_aliases(aliases)


def _quote_posix_single(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def _quote_powershell_single(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _profile_source_line(alias_file_path: Path, *, windows: bool) -> str:
    path_text = str(alias_file_path)
    if windows:
        quoted = _quote_powershell_single(path_text)
        return f". {quoted}"

    quoted = _quote_posix_single(path_text)
    return f"[ -f {quoted} ] && . {quoted}"


def _normalize_path_for_compare(path: Path, *, windows: bool) -> str:
    if windows:
        return ntpath.normcase(ntpath.normpath(str(path)))
    return posixpath.normpath(str(path))


def _paths_equal(left: Path, right: Path, *, windows: bool) -> bool:
    return _normalize_path_for_compare(left, windows=windows) == _normalize_path_for_compare(
        right,
        windows=windows,
    )


def resolve_manifest_path(
    *,
    os_name: str | None = None,
    home: Path | None = None,
    user_profile: str | None = None,
) -> Path:
    resolved_os = os.name if os_name is None else os_name

    if resolved_os == "nt":
        profile_base = user_profile
        if profile_base is None:
            profile_base = os.environ.get("USERPROFILE", "").strip()
        if home is not None:
            home_path = home
        elif profile_base:
            home_path = Path(profile_base).expanduser()
        else:
            home_path = Path.home()
        return home_path / ".ai-dev" / "managed-aliases-manifest.json"

    home_path = Path.home() if home is None else home
    return home_path / ".config" / "ai-dev" / "managed-aliases-manifest.json"


def resolve_installer_paths(
    *,
    os_name: str | None = None,
    shell_program: str | None = None,
    home: Path | None = None,
    user_profile: str | None = None,
) -> AliasInstallerPaths:
    resolved_os = os.name if os_name is None else os_name

    if resolved_os == "nt":
        profile_base = user_profile
        if profile_base is None:
            profile_base = os.environ.get("USERPROFILE", "").strip()
        if home is not None:
            home_path = home
        elif profile_base:
            home_path = Path(profile_base).expanduser()
        else:
            home_path = Path.home()

        profile_path = home_path / "Documents" / "WindowsPowerShell" / "Microsoft.PowerShell_profile.ps1"
        alias_file_path = home_path / ".ai-dev" / "aliases.ps1"
        manifest_path = resolve_manifest_path(
            os_name=resolved_os,
            home=home_path,
            user_profile=profile_base,
        )
        return AliasInstallerPaths(
            profile_path=profile_path,
            alias_file_path=alias_file_path,
            manifest_path=manifest_path,
        )

    home_path = Path.home() if home is None else home
    shell_value = shell_program
    if shell_value is None:
        shell_value = os.environ.get("SHELL", "").strip()

    shell_name = Path(shell_value).name.lower()
    if shell_name == "bash":
        profile_path = home_path / ".bashrc"
    elif shell_name == "zsh":
        profile_path = home_path / ".zshrc"
    elif shell_name:
        raise AliasInstallationError(
            "Unsupported shell for managed aliases: "
            f"{shell_name!r}. Set SHELL to bash or zsh."
        )
    else:
        raise AliasInstallationError(
            "Cannot determine shell for managed aliases. Set SHELL to bash or zsh."
        )

    alias_file_path = home_path / ".config" / "ai-dev" / "aliases.sh"
    manifest_path = resolve_manifest_path(os_name=resolved_os, home=home_path)
    return AliasInstallerPaths(
        profile_path=profile_path,
        alias_file_path=alias_file_path,
        manifest_path=manifest_path,
    )


def _write_text_file(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        write_text_atomic(path, text)
    except JsonFileError as exc:
        raise AliasInstallationError(str(exc)) from exc


def _write_alias_file(alias_file_path: Path, alias_text: str) -> None:
    _write_text_file(alias_file_path, alias_text)


def _write_profile(profile_path: Path, profile_text: str) -> None:
    _write_text_file(profile_path, profile_text)


def _manifest_from_state(
    *,
    aliases: dict[str, str],
    profile_path: Path,
    profile_text: str,
    alias_file_path: Path,
    alias_text: str,
) -> InstallationManifest:
    return InstallationManifest(
        version=MANIFEST_VERSION,
        profile_path=profile_path,
        profile_sha256=_sha256_text(profile_text),
        alias_file_path=alias_file_path,
        alias_file_sha256=_sha256_text(alias_text),
        aliases=dict(sorted(aliases.items(), key=lambda item: item[0])),
    )


def _load_manifest_safe(manifest_path: Path) -> InstallationManifest | None:
    try:
        return load_manifest(manifest_path)
    except InstallationManifestError as exc:
        raise AliasInstallationError(str(exc)) from exc


def _manifest_matches_alias_file(
    *,
    manifest: InstallationManifest | None,
    alias_file_path: Path,
    alias_text: str,
) -> bool:
    if manifest is None:
        return False
    if manifest.alias_file_path != alias_file_path:
        return False
    return manifest.alias_file_sha256 == _sha256_text(alias_text)


def _is_ai_dev_owned_alias_file(text: str) -> bool:
    return text.startswith(f"{_GENERATED_HEADER}\n") or text == _GENERATED_HEADER


def _ensure_alias_file_is_safe_to_manage(
    *,
    alias_file_path: Path,
    current_text: str,
    prior_manifest: InstallationManifest | None,
) -> None:
    if _manifest_matches_alias_file(
        manifest=prior_manifest,
        alias_file_path=alias_file_path,
        alias_text=current_text,
    ):
        return

    if _is_ai_dev_owned_alias_file(current_text):
        return

    raise AliasInstallationError(
        "Refusing to overwrite or remove non-managed alias file at "
        f"{alias_file_path}. The file does not match prior manifest ownership."
    )


def _ensure_manifest_owned_alias_file(
    *,
    alias_file_path: Path,
    prior_manifest: InstallationManifest,
    windows: bool,
) -> str:
    if not _paths_equal(
        alias_file_path,
        prior_manifest.alias_file_path,
        windows=windows,
    ):
        raise AliasInstallationError(
            "Refusing to remove migrated alias file because manifest alias path does not match target cleanup path: "
            f"{alias_file_path}."
        )

    if not alias_file_path.exists():
        raise AliasInstallationError(
            "Managed alias file recorded in manifest is missing at "
            f"{alias_file_path}. Manual recovery required before migration/remove-all."
        )

    alias_text = _read_text_or_empty(alias_file_path)
    if _sha256_text(alias_text) != prior_manifest.alias_file_sha256:
        raise AliasInstallationError(
            "Refusing to delete divergent managed alias file at "
            f"{alias_file_path}. The file no longer matches manifest digest. "
            "Manual recovery required."
        )

    return alias_text


def _snapshot_state(
    *,
    manifest_path: Path,
    manifest: InstallationManifest | None,
    file_paths: Iterable[Path],
) -> _InstallSnapshot:
    file_snapshot: dict[Path, tuple[bool, str]] = {}
    for path in sorted(set(file_paths), key=lambda item: str(item)):
        file_snapshot[path] = (path.exists(), _read_text_or_empty(path))

    return _InstallSnapshot(
        files=file_snapshot,
        manifest_exists=manifest_path.exists(),
        manifest=manifest,
    )


def _restore_from_snapshot(
    *,
    manifest_path: Path,
    snapshot: _InstallSnapshot,
) -> list[str]:
    failures: list[str] = []

    for path, (exists, text) in sorted(snapshot.files.items(), key=lambda item: str(item[0])):
        try:
            if exists:
                _write_text_file(path, text)
            elif path.exists():
                path.unlink()
        except Exception as exc:
            failures.append(f"restore file {path}: {exc}")

    try:
        if snapshot.manifest_exists:
            if snapshot.manifest is None:
                failures.append(
                    f"restore manifest {manifest_path}: original manifest content unavailable"
                )
            else:
                save_manifest(manifest_path, snapshot.manifest)
        elif manifest_path.exists():
            manifest_path.unlink()
    except Exception as exc:
        failures.append(f"restore manifest file {manifest_path}: {exc}")

    return failures


def _raise_failure_with_rollback(
    *,
    original_error: Exception,
    rollback_failures: list[str],
) -> None:
    if rollback_failures:
        joined = "; ".join(rollback_failures)
        raise AliasInstallationError(
            f"{original_error}; rollback failures: {joined}"
        ) from original_error

    raise AliasInstallationError(str(original_error)) from original_error


def apply_alias_reconciliation(
    desired: DesiredAliasState,
    *,
    installer_paths: AliasInstallerPaths | None = None,
    force_windows: bool | None = None,
) -> AliasApplySummary:
    is_windows = (os.name == "nt") if force_windows is None else force_windows

    resolved_os = "nt" if is_windows else os.name
    manifest_path = (
        installer_paths.manifest_path
        if installer_paths is not None
        else resolve_manifest_path(os_name=resolved_os)
    )
    previous_manifest = _load_manifest_safe(manifest_path)

    if not desired.aliases:
        if previous_manifest is None:
            return AliasApplySummary(
                aliases_configured=0,
                alias_file_changed=False,
                profile_changed=False,
                manifest_written=False,
                manifest_removed=False,
                outcome="no-op",
                alias_file_path=(installer_paths.alias_file_path if installer_paths else None),
                profile_path=(installer_paths.profile_path if installer_paths else None),
                manifest_path=manifest_path,
            )

        cleanup_alias_path = previous_manifest.alias_file_path
        cleanup_profile_path = previous_manifest.profile_path
        old_alias_text = _ensure_manifest_owned_alias_file(
            alias_file_path=cleanup_alias_path,
            prior_manifest=previous_manifest,
            windows=is_windows,
        )
        old_profile_text = _read_text_or_empty(cleanup_profile_path)
        profile_update = remove_managed_block(old_profile_text)
        alias_file_changed = cleanup_alias_path.exists()
        profile_changed = profile_update.changed
        manifest_removed = manifest_path.exists()

        snapshot = _snapshot_state(
            manifest_path=manifest_path,
            manifest=previous_manifest,
            file_paths=[cleanup_alias_path, cleanup_profile_path],
        )

        try:
            if cleanup_alias_path.exists():
                cleanup_alias_path.unlink()
            if profile_changed:
                _write_profile(cleanup_profile_path, profile_update.text)
            if manifest_removed:
                manifest_path.unlink()
        except Exception as exc:
            rollback_failures = _restore_from_snapshot(
                manifest_path=manifest_path,
                snapshot=snapshot,
            )
            _raise_failure_with_rollback(
                original_error=exc,
                rollback_failures=rollback_failures,
            )

        return AliasApplySummary(
            aliases_configured=0,
            alias_file_changed=alias_file_changed,
            profile_changed=profile_changed,
            manifest_written=False,
            manifest_removed=manifest_removed,
            outcome="removed-all",
            alias_file_path=cleanup_alias_path,
            profile_path=cleanup_profile_path,
            manifest_path=manifest_path,
            previous_alias_file_path=cleanup_alias_path,
            previous_profile_path=cleanup_profile_path,
        )

    target_paths = installer_paths or resolve_installer_paths(os_name=resolved_os)
    previous_alias_text = _read_text_or_empty(target_paths.alias_file_path)
    previous_profile_text = _read_text_or_empty(target_paths.profile_path)

    migration = False
    previous_alias_path: Path | None = None
    previous_profile_path: Path | None = None
    remove_old_alias = False
    remove_old_profile_block = False

    if previous_manifest is not None:
        previous_alias_path = previous_manifest.alias_file_path
        previous_profile_path = previous_manifest.profile_path
        migration = (
            not _paths_equal(previous_alias_path, target_paths.alias_file_path, windows=is_windows)
            or not _paths_equal(previous_profile_path, target_paths.profile_path, windows=is_windows)
        )

        if migration:
            _ensure_manifest_owned_alias_file(
                alias_file_path=previous_alias_path,
                prior_manifest=previous_manifest,
                windows=is_windows,
            )

            remove_old_alias = not _paths_equal(
                previous_alias_path,
                target_paths.alias_file_path,
                windows=is_windows,
            )
            remove_old_profile_block = not _paths_equal(
                previous_profile_path,
                target_paths.profile_path,
                windows=is_windows,
            )

    if target_paths.alias_file_path.exists():
        manifest_for_target = previous_manifest
        if (
            previous_manifest is not None
            and previous_alias_path is not None
            and not _paths_equal(previous_alias_path, target_paths.alias_file_path, windows=is_windows)
        ):
            manifest_for_target = None

        _ensure_alias_file_is_safe_to_manage(
            alias_file_path=target_paths.alias_file_path,
            current_text=previous_alias_text,
            prior_manifest=manifest_for_target,
        )

    alias_text = _render_alias_file(desired.aliases, windows=is_windows)
    source_line = _profile_source_line(target_paths.alias_file_path, windows=is_windows)

    try:
        profile_update = upsert_managed_block(previous_profile_text, source_line)
    except ProfileBlockError as exc:
        raise AliasInstallationError(str(exc)) from exc

    target_alias_changed = previous_alias_text != alias_text
    target_profile_changed = profile_update.changed

    snapshot_paths: list[Path] = [target_paths.alias_file_path, target_paths.profile_path]
    if migration and previous_alias_path is not None:
        snapshot_paths.append(previous_alias_path)
    if migration and previous_profile_path is not None:
        snapshot_paths.append(previous_profile_path)

    snapshot = _snapshot_state(
        manifest_path=manifest_path,
        manifest=previous_manifest,
        file_paths=snapshot_paths,
    )

    wrote_manifest = False
    old_alias_removed = False
    old_profile_cleaned = False
    try:
        if migration and remove_old_profile_block and previous_profile_path is not None:
            old_profile_text = _read_text_or_empty(previous_profile_path)
            old_profile_update = remove_managed_block(old_profile_text)
            if old_profile_update.changed:
                _write_profile(previous_profile_path, old_profile_update.text)
                old_profile_cleaned = True

        if migration and remove_old_alias and previous_alias_path is not None and previous_alias_path.exists():
            previous_alias_path.unlink()
            old_alias_removed = True

        if target_alias_changed:
            _write_alias_file(target_paths.alias_file_path, alias_text)

        if target_profile_changed:
            _write_profile(target_paths.profile_path, profile_update.text)

        final_profile_text = _read_text_or_empty(target_paths.profile_path)
        final_alias_text = _read_text_or_empty(target_paths.alias_file_path)
        manifest = _manifest_from_state(
            aliases=desired.aliases,
            profile_path=target_paths.profile_path,
            profile_text=final_profile_text,
            alias_file_path=target_paths.alias_file_path,
            alias_text=final_alias_text,
        )

        manifest_needs_write = (not manifest_path.exists()) or (previous_manifest != manifest)
        if manifest_needs_write:
            save_manifest(manifest_path, manifest)
            wrote_manifest = True
    except Exception as exc:
        rollback_failures = _restore_from_snapshot(
            manifest_path=manifest_path,
            snapshot=snapshot,
        )
        _raise_failure_with_rollback(
            original_error=exc,
            rollback_failures=rollback_failures,
        )

    alias_file_changed = target_alias_changed or old_alias_removed
    profile_changed = target_profile_changed or old_profile_cleaned
    if migration:
        outcome = "migrated"
    else:
        outcome = "applied" if (alias_file_changed or profile_changed or wrote_manifest) else "no-op"

    return AliasApplySummary(
        aliases_configured=len(desired.aliases),
        alias_file_changed=alias_file_changed,
        profile_changed=profile_changed,
        manifest_written=wrote_manifest,
        manifest_removed=False,
        outcome=outcome,
        alias_file_path=target_paths.alias_file_path,
        profile_path=target_paths.profile_path,
        manifest_path=manifest_path,
        previous_alias_file_path=(previous_alias_path if migration else None),
        previous_profile_path=(previous_profile_path if migration else None),
    )
