export const MAX_DIRECT_CHANGED_FILE_CONTENTS = 12;
export const MAX_DIRECT_FILE_CHARS = 12000;
export const MAX_DIRECT_DIFF_SAMPLE_FILES = 12;
export const MAX_DIRECT_DIFF_CHARS = 8000;
export const MAX_DIRECT_EXPECTED_DOC_CONTEXT_FILES = 12;
export const MAX_DIRECT_SCOPED_INDEX_CONTEXT_FILES = 20;
